apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunderbolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunderbolt
  template:
    metadata:
      labels:
        app: thunderbolt
    spec:
      containers:
        - name: web
          image: ghcr.io/the-most-secure-supply-chain-ever-maaan/thunderbolt@sha256:3b54e0886e5049a4a4088c3277f6515f30451a4335214323b893e8e0da3c9590
          ports:
            - containerPort: 5731
---
apiVersion: v1
kind: Service
metadata:
  name: thunderbolt
spec:
  selector:
    app: thunderbolt
  ports:
    - port: 80
      targetPort: 5731 # nginx port
---
