apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunderbolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunderbolt
  template:
    metadata:
      labels:
        app: thunderbolt
    spec:
      containers:
        - name: web
          image: ghcr.io/the-most-secure-supply-chain-ever-maaan/thunderbolt@sha256:eb9ffb6bf33380486d0a4b11d6e77b211ea44a92650e4c3dd32b00b67cf07397
          ports:
            - containerPort: 5731
---
apiVersion: v1
kind: Service
metadata:
  name: thunderbolt
spec:
  selector:
    app: thunderbolt
  ports:
    - port: 80
      targetPort: 5731 # nginx port
---
