apiVersion: apps/v1
kind: Deployment
metadata:
  name: thunderbolt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thunderbolt
  template:
    metadata:
      labels:
        app: thunderbolt
    spec:
      containers:
        - name: web
          image: ghcr.io/the-most-secure-supply-chain-ever-maaan/thunderbolt@sha256:687c151f8c4c2b355ae6964832328fd274a1012a1dd8f6591d774d7f667662e9
          ports:
            - containerPort: 5731
---
apiVersion: v1
kind: Service
metadata:
  name: thunderbolt
spec:
  selector:
    app: thunderbolt
  ports:
    - port: 80
      targetPort: 5731 # nginx port
---
