# cluster-config/argocd/application.yaml
# Bootstrappes manuelt. Se argocd/README.md for rekkefølge.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thunderbolt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/the-most-secure-supply-chain-ever-maaan/cluster-config
    targetRevision: main
    path: apps/thunderbolt
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true